### ISSUE TITLE
No support for recent Python versions

### ISSUE THREAD

**Issue by jkugler** [Yelp/virtualenv-tools#27]
According to https://pypi.org/project/virtualenv-tools3/ the last Python3 version support is 3.8. That appears to be true. Running under 3.11 generates this error:
```
Error in ./lib/python3.11/site-packages/rest_framework_simplejwt/__pycache__/compat.cpython-311.pyc {:level=>:info}
Traceback (most recent call last): {:level=>:info}
  File "/home/jkugler/.local/bin/virtualenv-tools", line 8, in <module> {:level=>:info}
    sys.exit(main()) {:level=>:info}
  File "/home/jkugler/.local/lib/python3.10/site-packages/virtualenv_tools.py", line 357, in main {:level=>:info}
    update_paths(venv, update_path) {:level=>:info}
  File "/home/jkugler/.local/lib/python3.10/site-packages/virtualenv_tools.py", line 230, in update_paths {:level=>:info}
    update_pycs(lib_dir, new_path) {:level=>:info}
  File "/home/jkugler/.local/lib/python3.10/site-packages/virtualenv_tools.py", line 180, in update_pycs {:level=>:info}
    update_pyc(filename, local_path) {:level=>:info}
  File "/home/jkugler/.local/lib/python3.10/site-packages/virtualenv_tools.py", line 122, in update_pyc {:level=>:info}
    code = marshal.load(f) {:level=>:info}
ValueError: bad marshal data (unknown type code) {:level=>:info}
```
Is there a timeline to update Python version support?

**Comment by jkugler** [comment]
One moment. This maybe be an error in the build tool. I'll keep y'all posted. :)

**Comment by asottile** [comment]
works fine for me -- just tried it on a 3.11 virtualenv with success -- the test suite also passes on 3.11

in the future I'd recommend trying to make an isolated case first before opening an issue!

**Comment by jkugler** [comment]
I apologize for the noise. Could `setup.py` be updated to show support for recent versions?

Thanks!
